name: Validate & Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node v${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm ci
      - name: Lint styles and code
        run: npm run lint

      - name: Build project
        run: npm run build
